### PR TITLE
upd: direnv integrity hash

### PR DESCRIPTION
**Pull request by wmertens**

### CODE REVIEW

**Comment by GTrunSec** [comment]
Could you update the `nix flake lock --update-input kroki-preprocessor` too?

Thanks.

**Comment by blaggacao** [comment]
Thanks, that was an oversight. :smile: 

Still some incoming speed improvements will probably land soon via: https://github.com/divnix/std/compare/main...direnv-test

**Comment by blaggacao** [comment]
@GTrunSec I still need to figure out how to best deal with `mdbook` support (+ kroki-pre-rendering). But some ideas are forming in my head w.r.t. `nix-community/nixago`.

**Comment by GTrunSec** [comment]
Could it be this implementation? kroki-APIs -> nix-parsec -> nixago ->mdbook ?

**Pull request merged**
